skip_non_tags: true
pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2022
configuration: Release

environment:
  fast_finish: true  # set this flag to immediately finish build once one of the jobs fails.
  solution_name: ScintillaNET_FindReplaceDialog.sln

before_build:
- cmd: dotnet restore %solution_name%

build:
  project: '%solution_name%'

  # MSBuild verbosity level
  verbosity: minimal

after_build:
  - dotnet pack ScintillaNET_FindReplaceDialog\ScintillaNET_FindReplaceDialog.csproj

deploy:
  - provider: NuGet
    api_key:
      secure: F+FEV17LBxIXlSSCC5LD2P9rhkpjGzzD34LaalIJRCSW+8mM9YeI08i9WU/0ZojP
    on:
      APPVEYOR_REPO_TAG: true
    artifact: /.*(\.|\.s)nupkg/

artifacts:
- path: Output\**\*.nupkg'